---
build_from:
    aarch64: ghcr.io/hassio-addons/base/aarch64:12.2.2
    amd64: ghcr.io/hassio-addons/base/amd64:12.2.2
    armhf: ghcr.io/hassio-addons/base/armhf:12.2.2
    armv7: ghcr.io/hassio-addons/base/armv7:12.2.2
    i386: ghcr.io/hassio-addons/base/i386:12.2.2
    arm64: ghcr.io/hassio-addons/base/arm64:12.2.2
codenotary:
  signer: richard+git@ohheyrj.co.uk
image: "ohheyrj/hassio-addon-octoprint-filament-manager-mqtt-{arch}"
shadow_repository: "ghcr.io/systemsmystery"
