---
name: Build Test

env:
  BUILD_ARGS: "--test"

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build $({ matrix.arch }) Octoprint Filament Manager MQTT Add-On
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # - name: Login to DockerHub
      #   if: env.BUILD_ARGS == '--docker-hub-check'
      #   uses: docker/login-action@v2.0.0
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Octoprint Filament Manager MQTT add-on"
        uses: home-assistant/builder@2022.07.0
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --${{ matrix.arch }} \
            --target /data/octoprint-filament-manager-mqtt \
            --addon