---
on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: release-please-action
      - name: Checkout the repository
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target /data/octoprint-filament-manager-mqtt 
        env:
          CAS_API_KEY: ${{ secrets.CAS_API_KEY }}
        if: ${{ steps.release.outputs.release_created }}
