---
on:
  push:
    branches:
      - main
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release please
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: release-please-action
  check:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Failed release
        if: ${{ ! needs.release.outputs.release_created }}
        run: exit 1
      - name: Passed
        if: ${{ needs.release.outputs.release_created }}
        run: exit 0
